### ISSUE TITLE
Link to issues broken on the Contributing page

### ISSUE THREAD

**Issue by jason-c-kwan** [Tiny-Earth/ScientificTeachingCourse#1]
I noticed that the link to the issues page is wrong on the contributing page. I think the root directory should be Tiny-Earth and not TinyEarth.

**Comment by snotskie** [comment]
Oh, thanks for the catch! Fixed here https://github.com/Tiny-Earth/DemoSite/commit/b4022a6cd7293f25a033c1e823918b41ac5ede21
